:icons: font
= Setting up a Postgres Database for AAP2

== Why

Given that the installer for AAP two actually supports creating and running a container rise version of grass why is it useful to install RN.

The AP two installer, as we have seen Support a very flexible, architecture choice, for example a complete all in one where everything including post runs on a single host to a completely distributed model, where each component runs on its own BM.

In addition, the installer allows the end-user to supply their own grass instance. This is a flexible option and allows for not only a separation of concerns, but for automation teams to leverage centrally, managed databases by dedicated database teams, but also the optioiNOTEn of using a cloud based DBA, such as RDS.

NOTE: important to understand the support model of using external pass grass, and it's beyond the scope of this lack lab to cover this.

* Databases are often IO bound and separation allows for the use of dedicated instances and IO optimization
** Cloud Providers for example support both IO-optimized instance types (NVMe drives etc)
** Cloud Providers also

NOTE: It is beyond the scope of this lab to cover the support implications of externally self hosted or cloud-hosted Postgres.

== Postgres Requirements

== How

This lab preplaces a simple Postgres installer already configured to work in our environment. It simple leverages the following role and collection

* `geerlingguy.postgresql`
* `community.postgresql`

. Change directory into the Postgres installer repository 
+

[source,sh]
----
cd postgres-for-aap2
----

. Explore the Postgres installer - it is quite simple in its construction
+

[source,sh]
----
tree -L 2
----
+
.Sample Output
[source,texinfo]
----
.
├── ansible.cfg
├── group_vars
│   └── aap2_databases.yml
├── install-postgresql.yml
├── inventory
├── README.adoc
└── requirments.yml
----
+

. If you like take a moment to explore the repository which is quite simple, perhaps the most interesting file being the `group_vars/aap2_databases.yml` primarily used for configuring the `geerlingguy.postgresql` role.
+
NOTE: It is the var file where we set the postgres password which will be used later by the AAP2 installer. For simplicity, we recommend you do not change it in this lab situation.

. Next let's install the necessary dependencies (role and collection) which have been isolated and versioned in the `requirements.yml` file, via `ansible-galaxy`
+

[source,sh,role=execute,subs=attributes+]
----
ansible-galaxy install -r requirments.yml
----
+

.Sample Output
[source,texinfo]
----
Starting galaxy role install process
- downloading role 'postgresql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-postgresql/archive/3.5.0.tar.gz
- extracting geerlingguy.postgresql to /home/devops/.ansible/roles/geerlingguy.postgresql
- geerlingguy.postgresql (3.5.0) was installed successfully
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-postgresql-3.2.0.tar.gz to /home/devops/.ansible/tmp/ansible-local-436544_pd24uz/tmpsp8y6798/community-postgresql-3.2.0-b6zf4udj
Installing 'community.postgresql:3.2.0' to '/home/devops/.ansible/collections/ansible_collections/community/postgresql'
community.postgresql:3.2.0 was installed successfully
----

. Finally run the installer playbook which simply acts as a wrapper around the role you just installed.
+

[source,sh,role=execute,subs=attributes+]
----
ansible-playbook install-postgresql.yml
----
+

.Sample Output
[source,texinfo]
----
<<PUT FREWSH output here>>
----
+

TIP: Several of the most common issues we see with remote Postgres installations include:
+
--
. **Ensuring that Postgres has listens on a network interfaces**: foo
. **Password authentication is setup correctly**: foo
. **Firewalls and Cloud Security Groups are configured**: e.g. In our case we have preconfigured AWS Security Groups
--
+
If you are curious as to the first 2 points, they are configured in `group_vars/aap2_databases.yml` and the role.

==== Basic Checklist for broken Postgres Installs

. `[]` Is it running!
. `[]` Can I access it locally (e.g.) *and* authenticate
. `[]` Can I access the port, typically 5432, across the network

== Summary



This module is now complete,


 In the next module we will unpack the AAP2 Containerized Installer and configure our inventory for installation.







== Initial Configuration

| NOTE: Now is a great time to add any of your favorite tools `rg`, `nvim` etc. You'll be on this host for ~90 minutes so take a moment to make it your own. 

. First, we will get our Ansible environment set up. 
+
TIP: Some of the packages we are installing are already installed. However, we are following the Installation Guide (LINK) here are it is worth seeing what dependencies are expected
+

[source,sh]
----
sudo dnf install -y ansible-core wget git rsync
----
+

.Sample Output
[source,texinfo]
----
Updating Subscription Management repositories.
Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)                                       126 kB/s | 4.5 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - AppStream - Advanced Update Support (RPMs)             130 kB/s | 4.5 kB     00:00
 <TRUNCATED>

 Installed:
  ansible-core-2.14.2-5.el9_2.x86_64                                 libnsl2-2.0.0-1.el9.x86_64
  libtirpc-1.3.3-1.el9.x86_64                                        mpdecimal-2.5.1-3.el9.x86_64
  python3.11-3.11.2-2.el9_2.1.x86_64                                 python3.11-cffi-1.15.1-1.el9.x86_64
  python3.11-cryptography-37.0.2-5.el9.x86_64                        python3.11-libs-3.11.2-2.el9_2.1.x86_64
  python3.11-pip-wheel-22.3.1-2.el9.noarch                           python3.11-ply-3.11-1.el9.noarch
  python3.11-pycparser-2.20-1.el9.noarch                             python3.11-pyyaml-6.0-1.el9.x86_64
  python3.11-setuptools-wheel-65.5.1-2.el9.noarch                    python3.11-six-1.16.0-1.el9.noarch
  sshpass-1.09-4.el9.x86_64

Complete!

----
+

Let's just check Ansible is installed correctly and it is working. In the home directory of the `devops` user there is an inventory it is all working.
+

[source,sh,role=execute]
----
[devops@bastion ~]$ ansible all -m ping -i multi-tier-inventory
----
+




We will be using the `community.postgresql` collection to install the PostgreSQL database server.


We will start by installing the `community.postgresql` collection. This collection will be used to install the PostgreSQL database server.

+
[source,sh,role=execute]
----
 ansible-galaxy collection install community.postgresql
----
+
[source,sh,role=execute]
----
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-postgresql-3.2.0.tar.gz to /home/devops/.ansible/tmp/ansible-local-31757gswwmzua/tmpgw8_marq/community-postgresql-3.2.0-7mkv5me6
Installing 'community.postgresql:3.2.0' to '/home/devops/.ansible/collections/ansible_collections/community/postgresql'
community.postgresql:3.2.0 was installed successfully
----



Extract the bundled installer and change into the directory.

* Mention x86 and ARM architectures are supported
* bundles and unbudles installers
** size of unbundled installers
** sie of bundled installers



[source,sh,role=execute]
----
[devops@bastion ~]$ tar -xvf ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64.tar.gz
----
.Output
[source,sh,role=execute]
----
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/collections/
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/collections/ansible_collections/
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/collections/ansible_collections/ansible/
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/collections/ansible_collections/ansible/controller/
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/collections/ansible_collections/ansible/controller/MANIFEST
.json

<TRUNCATED>

ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/bundle/images/ee-supported-rhel8.tar.gz
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/bundle/images/hub-rhel8.tar.gz
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/bundle/images/hub-web-rhel8.tar.gz
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/bundle/images/ee-29-rhel8.tar.gz
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/bundle/images/postgresql-13.tar.gz
ansible-automation-platform-containerized-setup-bundle-2.4-1-x86_64/bundle/images/redis-6.tar.gz
----


 as you watch the airport, you might notice that really what we're doing is where unpackaging I'm at sport collection that contains the controller installer and other collections. Then near the end, you may notice that the bundle extracts a number of compressed container images and this is primarily because the controller installer will use these images to deploy the controller and the hub.



. Change into the directory

. Examine the basic structure of the installer
+

[source,sh]
----
tree -L 2
----
+

.Sample Output
[source,texinfo]
----
.
├── bundle
│   └── images
├── collections
│   └── ansible_collections
├── inventory
└── README.md
----

