= Resources, Consoles, and SSH

For your convenience, this document simply contains links/resources, credentials, primary host (`bastion`), SSH, information and AAP2 Consoles. Be aware that AAP2 Consoles will not be available until you have finished the installation of those components.

[#resources]
== Resources

* link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html-single/containerized_ansible_automation_platform_installation_guide/index#doc-wrapper[Install Guide]
* 

[#consoles]
=== Ansible Automation Platform Consoles

All AAP2 Consoles Endpoints will *not* be available until after the installer has been run.

[cols="2,3"]
|===
| Automation Controller
|`http://aap2.{subdomain}:80`
| Automation Hub
|`http://aap2.{subdomain}:81`
| Automation EDA
|`http://aap2.{subdomain}:82`
|===
[WARNING]
====
The current Tech Preview does *not* have inbuilt support for TLS, the following end-points whilst accessible will generate a Browser Warning.
====

[cols="2,3"]
|===
| Automation Controller
|`https://aap2.{subdomain}:443`
| Automation Hub
|`https://aap2.{subdomain}:444`
| Automation EDA
|`https://aap2.{subdomain}:445`
|===


[#ssh]
=s== SSH Details

Your primary work machine is `bastion`, which is pre-configured for any internal SSH

[cols="1,1,3"]
|===
|ssh username |ssh password | ssh host
|{ssh_username}
|{ssh_password}
|{targethost}
|===
 
[source,sh,role=execute,subs=attributes+]
.ssh command:
----
ssh devops@bastion.{guid}.example.opentlc.com
----

